[environments.env1]
theme = "CodexEfy"
store = "CodexEfy"
password  = "moon"
ignore = "sections/header.liquid"

[environments.env2]
store = "another-store"
path = "./dist"
ignore = ["sections/announcement-bar.liquid", "sections/header.liquid"]
output = "json"
live = true
allow-live = true